spring:
  profiles:
    active: dev  # 기본 프로필 dev
  
  application:
    name: BobHub

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER}

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  forward-headers-strategy: framework
  servlet:
    session:
      cookie:
        name: JSESSIONID
        secure: true
        same-site: none

mybatis:
  mapper-locations: classpath:/mappers/*.xml
  type-aliases-package: com.bobhub.domain

